core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('api/', include('core.routers')),
    path('auth/', include('django_auth_oidc.urls')),
    path("", include("events.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls.conf import path

from events.views import CategoryListView, EventCreateView, EventDetailView, EventInternalDetailView, EventListView, EventUpdateView, LandingView, MyEventList, ReviewEventList, category_detail, ical_view

app_name = "events"

urlpatterns = [
    path("category/", CategoryListView.as_view(), name="category_list"),
    path("category/<int:pk>/", category_detail, name="category_detail"),
    path("<int:pk>/", EventDetailView.as_view(), name="event_detail"),
    path("<int:pk>/internal/",
         EventInternalDetailView.as_view(),
         name="event_internal"),
    path("<int:pk>/update/", EventUpdateView.as_view(), name="event_update"),
    path("<int:pk>/ical/", ical_view, name="event_ical"),
    path("create/", EventCreateView.as_view(), name="event_create"),
    path("events/", EventListView.as_view(), name="event_list"),
    path("my/", MyEventList.as_view(), name="my_events"),
    path("review/", ReviewEventList.as_view(), name="review_events"),
    path("", LandingView.as_view(), name="landing"),
]

events/models.py
"""
Model definitions for the events app
"""
from urllib.parse import quote
import bleach
from uuid import uuid4

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.query_utils import Q
from django.urls.base import reverse
from django.utils.translation import gettext_lazy as _
from djrichtextfield.models import RichTextField

from events.rocket import create_discussion


class Category(models.Model):
    """
    Category of events, can include: workshop, flyer
    """
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    language_code = models.CharField(max_length=12, choices=settings.LANGUAGES)
    icon = models.FileField(blank=True)

    def __str__(self):
        return self.name


class Channel(models.Model):
    name = models.CharField(max_length=255)
    rid = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    """
    A single event
    """
    DRAFT = 'draft'
    REVIEW = 'review'
    PUBLIC = 'public'
    HIDDEN = 'hidden'

    STATES = (
        (DRAFT, _('Entwurf')),
        (REVIEW, _('Review')),
        (PUBLIC, _('Öffentlich')),
        (HIDDEN, _('Versteckt')),
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    title = models.CharField(
        max_length=255,
        verbose_name=_("Titel"),
        help_text=_("Titel deiner Veranstaltung"),
    )
    date = models.DateTimeField(
        verbose_name=_("Datum"),
        help_text=_("Datum und Zeit"),
    )
    duration = models.DurationField(verbose_name=_("Dauer"))
    language_code = models.CharField(max_length=12, choices=settings.LANGUAGES)
    description = RichTextField(
        sanitizer=lambda text: bleach.clean(text,
                                            tags=bleach.sanitizer.ALLOWED_TAGS
                                            + ['p', 'h2', 'h3', 'h4']),
        help_text=_("Um was geht es bei deiner Veranstaltung?"),
        verbose_name=_("Beschreibung"),
    )

    owner = models.ForeignKey(get_user_model(), models.CASCADE)
    state = models.CharField(
        choices=STATES,
        default=DRAFT,
        max_length=12,
        help_text=
        _("Sobald dein Event bereit ist, kannst du ihn auf Review stellen, damit er freigeschaltet wird."
          ))
    category = models.ForeignKey(Category,
                                 models.CASCADE,
                                 verbose_name=_("Kategorie"))
    internal_id = models.UUIDField(default=uuid4)
    image = models.ImageField(
        verbose_name=_("Bild"),
        blank=True,
        upload_to="images/%Y/%m/%d/",
    )

    is_online = models.BooleanField(
        verbose_name=_("Kann man bei deinem Event online teilnehmen?"), )
    is_offline = models.BooleanField(
        verbose_name=_("Kann man beim Event vor Ort teilnehmen?"), )

    link = models.URLField(
        blank=True,
        verbose_name=_("Link"),
        help_text=_(
            "Link zu deiner Veranstaltung, oder zu einem Anmeldeformular"),
    )

    street = models.CharField(
        max_length=200,
        blank=True,
        verbose_name=_("Strasse"),
    )
    city = models.CharField(max_length=200, blank=True, verbose_name=_("Ort"))
    zip_code = models.CharField(
        max_length=10,
        blank=True,
        verbose_name=_("PLZ"),
    )

    room = models.ForeignKey(
        Channel,
        models.SET_NULL,
        blank=True,
        null=True,
        verbose_name=_("Rocketchat-Raum"),
        help_text=
        _("Wähle einen Raum von Rocket-Chat aus, um in diesem automatisch eine Diskussion "
          "zu starten um den Event zu planen. Du kannst es auch leer lassen."),
    )
    discussion_id = models.CharField(max_length=200, blank=True)

    def has_edit_permission(self, user):
        """Checks if the given user may edit the event."""
        if user == self.owner:
            return True
        return EditAccess.objects.filter(
            user=user,
            event=self,
            state=EditAccess.GRANTED,
        ).exists()

    def map_url(self):
        query = f"{self.street}, {self.zip_code} {self.city}"
        return f"https://www.google.com/maps/search/?api=1&query={quote(query)}"

    class Meta:
        constraints = [
            models.CheckConstraint(
                check=Q(is_offline=False)
                | (~Q(street__exact='') & ~Q(city__exact='')
                   & ~Q(zip_code__exact='')),
                name="offline_event_has_address",
            ),
        ]
        ordering = ['date']
        permissions = [
            ("publish_event", _("Kann Events publizieren.")),
        ]

    def __str__(self):
        return f"Event: {self.title}"

    def get_absolute_url(self):
        return reverse("events:event_detail", args=(self.pk, ))

    def chat_link(self):
        return f"https://{settings.ROCKET_DOMAIN}/channel/{self.discussion_id}"

    def save(self, *args, **kwargs):
        if self.room and not self.discussion_id:
            self.discussion_id = create_discussion(
                self.room.rid,
                self.title,
            )
        self.language_code = self.category.language_code
        return super().save(*args, **kwargs)


class EditAccess(models.Model):
    """
    Gain access to edit an event through this.
    """
    PENDING = 0
    GRANTED = 1
    DENIED = 2

    STATES = (
        (_("pending"), PENDING),
        (_("granted"), GRANTED),
        (_("denied"), DENIED),
    )

    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        related_name="editors",
    )

    user = models.ForeignKey(get_user_model(), models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    state = models.IntegerField(choices=STATES)

    def __str__(self):
        return f"EditAccess: {self.user.username}@{self.event.slug}"

events/forms.py
from typing import Any, Dict

from django.core.exceptions import ValidationError
from events.models import Event
from django.utils.translation import gettext as _
from django import forms


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'title', 'description', 'date', 'duration', 'category', 'image',
            'is_online', 'is_offline', 'link', 'street', 'city', 'zip_code',
            'room', 'state'
        ]
        widgets = {
            'duration':
            forms.TextInput(attrs={
                'pattern': '[0-9]{2}:[0-9]{2}(:[0-9]{2})?',
                'placeholder': 'HH:MM'
            }),
            'date':
            forms.DateTimeInput(format="%Y-%m-%d %H:%M:%S")
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if (self.user is
                None) or (not self.user.has_perm('event.publish_event')):
            if self.instance.state == Event.PUBLIC:
                self.fields['state'].choices = (
                    (Event.DRAFT, _("Entwurf")),
                    (Event.REVIEW, _("Review")),
                    (Event.PUBLIC, _("Publiziert")),
                )
            else:
                self.fields['state'].choices = (
                    (Event.DRAFT, _("Entwurf")),
                    (Event.REVIEW, _("Review")),
                )

    def clean(self) -> Dict[str, Any]:
        if self.cleaned_data['is_offline'] and not (
                self.cleaned_data['street'] and self.cleaned_data['city'] and
                self.cleaned_data['city'] and self.cleaned_data['zip_code']):
            self.add_error(
                "street",
                ValidationError(
                    _("Ein offline Event braucht eine vollständige Adresse.")))
        return super().clean()

events/views.py
from datetime import datetime
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http.response import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import get_language
from django.views.generic import DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django_filters.views import FilterView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from events.filters import EventFilter
from events.forms import EventForm
from events.models import Category, Event

from django.utils.translation import gettext as _
# Create your views here.


class EventDetailView(DetailView):
    model = Event

    def get_queryset(self) -> QuerySet:
        if self.request.user.is_authenticated:
            return super().get_queryset()
        return super().get_queryset().filter(state=Event.PUBLIC)


class EventInternalDetailView(LoginRequiredMixin, DetailView):
    model = Event
    template_name = 'events/event_internal.html'


class BaseEventView(FilterView):
    model = Event
    template_name = 'events/event_list.html'
    filterset_class = EventFilter
    paginate_by = 20

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        result = super().get_context_data(**kwargs)
        if category_pk := self.request.GET.get('category'):
            result['title'] = _("Kategorie: ") + Category.objects.get(
                pk=category_pk).name
        else:
            result['title'] = self.title
        return result


class EventListView(BaseEventView):
    title = _("Alle Events")

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Event.objects.filter(
                date__date__gte=timezone.now().date(),
                language_code=get_language(),
            )
        return Event.objects.filter(
            date__date__gte=timezone.now().date(),
            language_code=get_language(),
            state=Event.PUBLIC,
        )


class MyEventList(LoginRequiredMixin, BaseEventView):
    title = _("Meine Events")

    def get_queryset(self):
        return Event.objects.filter(owner=self.request.user, )


class ReviewEventList(PermissionRequiredMixin, BaseEventView):
    permission_required = "event.publish_event"
    title = _("Review Events")

    def get_queryset(self):
        return Event.objects.filter(state=Event.REVIEW)


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm
    template_name = 'events/event_create.html'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        form.instance.owner = self.request.user
        form.instance.language_code = get_language()

        return super().form_valid(form)

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'events/event_update.html'

    def get_queryset(self) -> QuerySet:
        if self.request.user.has_perm('event.publish_event'):
            return super().get_queryset()

        return super().get_queryset().filter(owner=self.request.user)

    def get_form_kwargs(self) -> Dict[str, Any]:
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs


class CategoryListView(ListView):
    model = Category

    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(language_code=get_language())


class LandingView(TemplateView):
    template_name = 'events/landing.html'


def category_detail(request, pk):
    return redirect(reverse('events:event_list') + f"?category={pk}")


def format_for_ical(d):
    return datetime.strftime(d, "%Y%m%dT%H%M%S")


def ical_view(request, pk):
    response = HttpResponse(
        content_type="text/calendar, text/x-vcalendar, application/hbs-vcs")
    response["Content-Disposition"] = 'attachment; filename="event.ics"'
    event = Event.objects.get(pk=pk)
    response.write(f"""BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Collab-EVENT Tool//v0.1
BEGIN:VEVENT
UID:{event.pk}@{request.get_host()}
CREATED:{format_for_ical(event.created)}Z
DTSTAMP:{format_for_ical(event.updated)}Z
DTSTART:{format_for_ical(event.date)}Z
DTEND:{format_for_ical(event.date + event.duration)}Z
SUMMARY:{event.title}
DESCRIPTION:https://{request.get_host()}{reverse("events:event_detail", args=(event.pk,))}
END:VEVENT
END:VCALENDAR
""")
    return response

events/templates/events/category_detail.html
{% extends "base.html" %}

events/templates/events/category_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Kategorien" %}{% endblock %}


{% block content %}
<header>
  <h2>{% trans "Kategorien" %}</h2>
</header>
<section class="categories">
  {% for category in category_list %}
  <article class="category">
    <a href="{% url 'events:category_detail' category.pk %}">
      <img src="{{category.icon.url}}" />
      <h3>{{category.name}}</h3>
    </a>
  </article>
  {% endfor %}
</section>
{% endblock %}

events/templates/events/event_create.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Event erstellen' %}{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form}}
  <div class="buttons">
    <button type="submit">{% trans 'Erstellen' %}</button>
  </div>
</form>
{% endblock %}


{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block script %}
{{form.media}}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/{{request.LANGUAGE_CODE}}.js"></script>
<script>
  const flatpickrConfig = {
      enableTime: true,
      altInput: true,
      altFormat: "j.m.Y H:i",
      dateFormat: "Y-m-dTH:i",
      locale: "{{request.LANGUAGE_CODE}}"  // locale for this instance only
    };
    flatpickr("#id_date", flatpickrConfig);
</script>
{% endblock %}

events/templates/events/event_detail.html
{% extends "base.html" %}
{% load i18n share %}

{% block title %}{{event.title}}{% endblock %}

{% block content %}
<h1 class="event-title">{{event.title}}</h1>
<div class="detail">
  <section class="event-info">
    {% if event.is_offline %}
    <a class="location" href="{{event.map_url}}" target="_blank">
      {{event.street}}, {{event.city}}, {{event.zip_code}}
    </a>
    {% endif %}
    <time class="time" datetime="{{event.date|date:"c"}}">
      {{event.date|date:"d. M. H:i"}}
    </time>
    {% if event.is_online %}
    <a class="event-link" target="_blank" href="{{event.link}}">{{event.link|truncatechars:40}}</a>
    {% endif %}

    <div class="description">
      {{event.description|safe}}
    </div>
  </section>
  {% if event.image %}
  <section class="image">
    <img src="{{event.image.url}}"/>
  </section>
  {% endif %}
</div>
<section class="buttons">
  <a class="button" href="{% facebook request.build_absolute_uri %}">Facebook</a>
  <a class="button" href="{% twitter request.build_absolute_uri %}">Twitter</a>
  <a class="button" href="{% mail request.build_absolute_uri event.title %}">E-Mail</a>
  <a class="button" href="{% linkedin request.build_absolute_uri event.title %}">LinkedIn</a>
</section>

{% if request.user.is_authenticated %}
<div class="internal buttons">
  {% if event.owner == request.user or perms.publish_event %}
  <a class="button" href="{% url 'events:event_update' event.pk %}">
    {% trans "Bearbeiten" %}
  </a>
  {% endif %}
  {% if event.discussion_id %}
  <a class="button" href="{{event.chat_link}}" target="_blank">
    {% trans "Chat" %}
  </a>
  {% endif %}
</div>
{% endif %}
{% endblock %}

events/templates/events/event_internal.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ event.title }}{% endblock %}

{% block content %}
<h2>{{event.title}}</h2>

{% endblock %}

events/templates/events/event_list.html
{% extends "base.html" %}
{% load i18n utils static %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<header class="content">
  <h2>{{title}}</h2>
  <div class="buttons">
    <button id="sidePanelToggle">
      {% trans 'Filter' %}
    </button>
  </div>
</header>
<section class="events">
  {% for event in event_list %}
  <article class="event">
    <a class="date" href="{% url 'events:event_detail' event.pk %}">
      <span class="day">
        {{event.date|date:"d"}}
      </span>
      <span class="month">
        {{event.date|date:"M"}}
      </span>
    </a>
    <div class="info">
      <h3><a href="{% url 'events:event_detail' event.pk %}">{{event.title}}</a></h3>
      <div class="where-and-when">
        {% if event.city %}
        {{event.city}} | {% endif %}{{event.date|date:"H:i"}}
      </div>
      <div class="icons">
        {% if event.is_offline %}
        <a href="{{event.map_url}}" title="{% trans "Ort auf Google Maps" %}" target="_blank">
          <img src="{% static 'icons/map-pin-line.svg' %}" />
        </a>
        {% endif %}
        {% if event.link %}
        <a href="{{event.link}}" title="{% trans "Veranstaltungslink" %}" target="_blank">
          <img src="{% static 'icons/link.svg' %}" />
        </a>
        {% endif %}
        <a href="{% url 'events:category_detail' event.category.pk %}" title="{{event.category.name}}">
          <img src="{{event.category.icon.url}}"/>
        </a>
        {% if request.user.is_authenticated %}
        {% if event.owner == request.user %}
        <a href="{% url 'events:event_update' event.pk %}" title="{% trans "Bearbeiten" %}">
          <img src="{% static 'icons/edit-line.svg' %}" />
        </a>
        {% endif %}
        {% if event.discussion_id %}
        <a href="{{event.chat_link}}" title="{% trans "Interner Chat" %}" target="_blank">
          <img src="{% static 'icons/chat-1-line.svg' %}" />
        </a>
        {% endif %}
        {% comment %}
        <a href="{% url 'events:event_internal' event.pk %}" title="{% trans "Intern" %}">
          <img src="{% static 'icons/admin-line.svg' %}" />
        </a>
        {% endcomment %}
        {% endif %}
        <a href="{% url 'events:event_detail' event.pk %}" title="{% trans "Intern" %}">
          <img src="{% static 'icons/eye-line.svg' %}" />
        </a>
        <a href="{% url 'events:event_ical' event.pk %}">
          <img src="{% static 'icons/calendar-line.svg' %}" />
        </a>
      </div>
    </div>
    {% if event.image %}
    <a class="image" href="{% url 'events:event_detail' event.pk %}">
      <img src="{{event.image.url}}" />
    </a>
    {% endif %}
  </article>
  {% empty %}
  <p>
  {% if request.user.is_authenticated %}
  {% url 'events:event_create' as create_url %}
  {% blocktranslate %}Leider keine Events gefunden. <a href="{{create_url}}">Erstelle einen!</a>{% endblocktranslate %}
  {% else %}
  {% url 'django_auth_oidc:login' as login_url %}
  {% blocktranslate %}Leider keine Events gefunden. Melde dich <a href="{{login_url}}">jetzt hier</a> an und erstelle einen!{% endblocktranslate %}
  {% endif %}
  </p>
  {% endfor %}
</section>
<section class="pagination">
  <div class="previous">
    {% if page_obj.has_previous %}
    <a class="page button" href="?{% param_replace page=page_obj.previous_page_number %}">{% trans "Zurück" %}</a>
    {% endif %}
  </div>

  <div class="next">
    {% if page_obj.has_next %}
    <a class="page button" href="?{% param_replace page=page_obj.next_page_number %}">{% trans "Weiter" %}</a>
    {% endif %}
  </div>
</section>
{% endblock %}

{% block aside %}
<form action="" method="get" id="filterForm">
  {{filter.form}}
  <div class="buttons">
    <button type="submit">{% trans 'Anwenden' %}</button>
  </div>
</form>
{% endblock %}

{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

{% endblock %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/{{request.LANGUAGE_CODE}}.js"></script>
<script>
  const flatpickrConfig = {
      altInput: true,
      altFormat: "j. M. Y",
      dateFormat: "Y-m-d",
      locale: "{{request.LANGUAGE_CODE}}",  // locale for this instance only
    };
    flatpickr("#id_date_gt", flatpickrConfig);
    flatpickr("#id_date_lt", flatpickrConfig);
</script>
{% endblock %}

events/templates/events/event_update.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Event bearbeiten' %}{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form}}
  <div class="buttons">
    <button type="submit">{% trans 'Speichern' %}</button>
    <a class="button" href="{% url 'events:event_detail' event.pk %}">{% trans "Zurück" %}</a>
  </div>
</form>
{% endblock %}


{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
{% endblock %}

{% block script %}
{{form.media}}
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://npmcdn.com/flatpickr/dist/l10n/{{request.LANGUAGE_CODE}}.js"></script>
<script>
  const flatpickrConfig = {
      enableTime: true,
      altInput: true,
      altFormat: "j.m.Y H:i",
      dateFormat: "Y-m-dTH:i",
      locale: "{{request.LANGUAGE_CODE}}"  // locale for this instance only
    };
    flatpickr("#id_date", flatpickrConfig);
</script>
{% endblock %}

events/templates/events/landing.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% trans 'We Are the 99%' %}{% endblock %}

{% block style %}
<style>
main {
  background: url("{% static 'landing_image.jpg' %}"), #0000005e;
  background-size: cover;
  background-position: center;
  background-blend-mode: color;
}
.form-center {
  color: var(--white);
}
body > header > nav > a {
  color: var(--white);
}
h1 {
  text-transform: uppercase;
}
p {
  margin-bottom: 2em;
}
</style>
{% endblock %}

{% block content %}
<div class="form-center">
  <h1>{% trans "Suche nach Anlässen in deiner Nähe" %}</h1>
  <p>
  {% blocktranslate %}Du willst wissen, wann die nächste Bildungsveranstaltung oder die nächste Flyeraktion in deiner Region stattfindet? Diese Seite gibt dir einen Überblick über alle geplanten Verantstaltungen. Eingeloggt kannst du auch selbst Events eintragen,die du organisierst. Öffentliche Verantstaltungen werden noch kurz überprüft, bevor sie dann auf der Webseite aufgeschaltet werden.{% endblocktranslate %}
  </p>
  <form action="{% url 'events:event_list' %}" method="get">
    <input type="text" name="search" id="search" placeholder="{% trans 'Suche eine Veranstaltung!' %}"/>
    <button type="submit" id="go">{% trans 'Los' %}</button>
  </form>
</div>
{% endblock %}